# Generated by Django 4.1.4 on 2023-01-02 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bon_Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_HT_BL', models.IntegerField()),
                ('Total_TTC_BL', models.IntegerField()),
                ('Remise_BL', models.IntegerField()),
                ('Date_BL', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_client', models.CharField(max_length=50)),
                ('Prenom_client', models.CharField(max_length=50)),
                ('Adr_client', models.CharField(max_length=50)),
                ('Tel_client', models.IntegerField(verbose_name=10)),
                ('Credit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Fournisseur', models.CharField(max_length=50)),
                ('Prenom_Fournisseur', models.CharField(max_length=50)),
                ('Adr_Fournisseur', models.CharField(max_length=50)),
                ('Tel_Fournisseur', models.IntegerField(verbose_name=10)),
                ('Email_Fournisseur', models.CharField(max_length=30)),
                ('Solde_Fournisseur', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_produit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_achat_Stock', models.IntegerField(default=0)),
                ('Total_vente_Stock', models.IntegerField(default=0)),
                ('Adr_Stock', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Vente', models.IntegerField()),
                ('Montant', models.IntegerField()),
                ('Date_Vente', models.DateField(auto_now_add=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.client')),
            ],
        ),
        migrations.CreateModel(
            name='Stocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte_stocker', models.IntegerField()),
                ('Date_stocker', models.DateField(auto_now_add=True)),
                ('Produits', models.ManyToManyField(to='application.product')),
                ('Stocks', models.ManyToManyField(to='application.stock')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Type_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.product_type'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_HT_Facture', models.IntegerField()),
                ('Total_TTC_Facture', models.IntegerField()),
                ('Remise_Facture', models.IntegerField()),
                ('Date_Facture', models.DateField(auto_now_add=True)),
                ('TVA', models.IntegerField(default=19)),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Etablire_facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte_Facture', models.IntegerField()),
                ('Prix_HT_Facture', models.IntegerField()),
                ('Prix_Vente_Facture', models.IntegerField()),
                ('Factures', models.ManyToManyField(to='application.facture')),
                ('Produits', models.ManyToManyField(to='application.product')),
            ],
        ),
        migrations.CreateModel(
            name='Etablire_BL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte_BL', models.IntegerField()),
                ('Prix_HT_BL', models.IntegerField()),
                ('Prix_Vente_BL', models.IntegerField()),
                ('Bons', models.ManyToManyField(to='application.bon_livraison')),
                ('Produits', models.ManyToManyField(to='application.product')),
            ],
        ),
        migrations.CreateModel(
            name='Effectuer_vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte_vente', models.IntegerField()),
                ('Produits', models.ManyToManyField(to='application.product')),
                ('Ventes', models.ManyToManyField(to='application.vente')),
            ],
        ),
        migrations.CreateModel(
            name='Destocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte_destocker', models.IntegerField()),
                ('Motif', models.CharField(max_length=50)),
                ('Produits', models.ManyToManyField(to='application.product')),
                ('Stocks', models.ManyToManyField(to='application.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qte_cmd', models.IntegerField()),
                ('Commandes', models.ManyToManyField(to='application.bon_livraison')),
                ('Produits', models.ManyToManyField(to='application.product')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_BC', models.DateField(auto_now_add=True)),
                ('Fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='bon_livraison',
            name='Fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.fournisseur'),
        ),
    ]
