# Generated by Django 4.1.4 on 2023-01-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='Tel_Fournisseur',
            field=models.IntegerField(),
        ),
    ]
