# Generated by Django 4.1.4 on 2023-01-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_commander_commandes_remove_commander_produits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='produits',
            field=models.ManyToManyField(through='application.Etablire_facture', to='application.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='factures',
            field=models.ManyToManyField(through='application.Etablire_facture', to='application.facture'),
        ),
        migrations.AlterField(
            model_name='etablire_facture',
            name='Factures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='application.facture'),
        ),
        migrations.AlterField(
            model_name='etablire_facture',
            name='Produits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produitsFACTURE', to='application.product'),
        ),
    ]
