# Generated by Django 4.1.4 on 2023-01-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_facture_produits_product_factures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='Total_HT_Facture',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='Total_TTC_Facture',
        ),
    ]
