# Generated by Django 4.1.4 on 2023-01-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_remove_facture_total_ht_facture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bon_livraison',
            name='Total_HT_BL',
        ),
        migrations.RemoveField(
            model_name='bon_livraison',
            name='Total_TTC_BL',
        ),
        migrations.AddField(
            model_name='bon_livraison',
            name='produits',
            field=models.ManyToManyField(through='application.Etablire_BL', to='application.product'),
        ),
        migrations.AddField(
            model_name='commander',
            name='commandes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cmd', to='application.commande'),
        ),
        migrations.AddField(
            model_name='etablire_bl',
            name='BLs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BL', to='application.bon_livraison'),
        ),
        migrations.AddField(
            model_name='etablire_bl',
            name='Produits_BL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produitsBL', to='application.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='BLs',
            field=models.ManyToManyField(through='application.Etablire_BL', to='application.bon_livraison'),
        ),
    ]
