# Generated by Django 4.1.4 on 2023-01-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_bon_livraison_total_ht_bl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='Produits',
            field=models.ManyToManyField(through='application.Commander', to='application.product'),
        ),
        migrations.AddField(
            model_name='commander',
            name='Produits_cmd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produitsCmd', to='application.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='commandes',
            field=models.ManyToManyField(through='application.Commander', to='application.commande'),
        ),
    ]
