# Generated by Django 4.1.4 on 2023-01-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_commande_produits_commander_produits_cmd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon_livraison',
            name='montant_payé_BL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_payé_facture',
            field=models.IntegerField(default=0),
        ),
    ]
