# Generated by Django 4.1.4 on 2023-01-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_bon_livraison_montant_payé_bl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon_livraison',
            name='BL_payé',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_payé',
            field=models.BooleanField(default=True),
        ),
    ]
