# Generated by Django 4.1.4 on 2023-01-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_bon_livraison_bl_payé_facture_facture_payé'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bon_livraison',
            name='montant_payé_BL',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant_payé_facture',
        ),
    ]
