# Generated by Django 4.1.4 on 2023-01-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_bon_livraison_montant_payé_bl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bon_livraison',
            old_name='Fournisseur',
            new_name='Fournisseurs',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='Fournisseur',
            new_name='Fournisseurs',
        ),
    ]
