# Generated by Django 4.1.4 on 2023-01-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_rename_fournisseur_bon_livraison_fournisseurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Total_achat_Stock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Total_vente_Stock',
        ),
    ]
