# Generated by Django 4.1.4 on 2023-01-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_stock_total_achat_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='Total_Vente',
        ),
    ]
