# Generated by Django 4.1.4 on 2023-01-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_remove_vente_total_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocker',
            name='Prix_HT_Produit',
            field=models.IntegerField(default=0),
        ),
    ]
