# Generated by Django 4.1.4 on 2023-01-11 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_stocker_prix_ht_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectuer_vente',
            name='Produits_BL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='application.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='ventes',
            field=models.ManyToManyField(through='application.Effectuer_vente', to='application.vente'),
        ),
        migrations.AddField(
            model_name='vente',
            name='Produits',
            field=models.ManyToManyField(through='application.Effectuer_vente', to='application.product'),
        ),
        migrations.RemoveField(
            model_name='effectuer_vente',
            name='Ventes',
        ),
        migrations.AddField(
            model_name='effectuer_vente',
            name='Ventes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vente', to='application.vente'),
        ),
    ]
