# Generated by Django 4.1.4 on 2023-01-11 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_effectuer_vente_produits_bl_product_ventes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effectuer_vente',
            old_name='Produits_BL',
            new_name='Produits_vente',
        ),
    ]
