# Generated by Django 4.1.4 on 2023-01-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_stocker_prix_vente_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Date_stocker',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Prix_HT_Produit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Prix_Vente_Produit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Qte_stocker',
            field=models.IntegerField(default=0),
        ),
    ]
