# Generated by Django 4.1.4 on 2023-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocker',
            name='Produits',
        ),
        migrations.RemoveField(
            model_name='stocker',
            name='Stocks',
        ),
        migrations.AddField(
            model_name='product',
            name='Motif',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='Qte_destocker',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Destocker',
        ),
        migrations.DeleteModel(
            name='Stocker',
        ),
    ]
