# Generated by Django 4.1.4 on 2023-01-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_alter_vente_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effectuer_vente',
            name='Produits',
        ),
    ]
